---
title: "Todo with Postgres and Ruby"
type: "challenge"
description: >
  "Adapts todo list app for inserting into and retrieving from a PostgreSQL
  database using Ruby."
tags: "databases, relational-databases, sql, sql-insert"
ignore:
- "todo-with-postgres-and-ruby.md"
